---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_for_busser: false
  require_ansible_omnibus: false
  ansible_version: 2.7.10-1ppa~trusty
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ignore_paths_from_root:
    - .kitchen

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: ubuntu:14.04
      platform: ubuntu
      provision_command:
        - apt-get install -y apt-transport-https

verifier:
  name: serverspec
  default_pattern: true
  sudo_path: true

suites:
  - name: default
    driver:
      network:
        - ["private_network", { ip: "172.16.129.171" }]

transport:
  forward_agent: true
