---

# SNI related error occurs if using python < v2.7.9
#- name: Download and install influxdb apt public signing key
#  apt_key:
#    url:   "{{ influxdb_signing_key_url }}"
#    state: present

- name: Download influxdb apt public signing key
  command:
      wget -q "{{ influxdb_signing_key_url }}" -O /var/tmp/influxdb.key
  args:
    creates: /var/tmp/influxdb.key

- name: Install influxdb apt public signing key
  apt_key:
    file:  /var/tmp/influxdb.key
    state: present
    
# Currently this is failing in ubuntu 14.04 With : Failed to fetch https://repos.influxdata.com/ubuntu/dists/trusty/stable/binary-amd64/Packages
# gnutls_handshake() failed: A TLS packet with unexpected length was received.
# Commenting this out for now. We need to upgrade ubuntu to fix it or install a specific version with dpkg.

 - name: Add influxdb apt repository definition to apt sources list
   apt_repository:
     repo:         "{{ influxdb_apt_repo }}"
     update_cache: yes
     state:        present

- name: Install influxdb
  apt: 
    name:  "influxdb={{ influxdb_version|default('*') }}"
    state: present
